### ISSUE TITLE
Is simplescope.py scope server sufficient 

### ISSUE THREAD

**Issue by joegle** [cmusatyalab/dermshare#1]
Section "Scope server" of README.md says "An example scope server is provided in simplescope."
Is simplescope/simplescope.py fully functional and do we still need to configure ~/.diamond/CERTS ~/.diamond/NEWSCOPE files? Thanks

**Comment by bgilbert** [comment]
The issue tracker is for issues.  Please use the [mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/dermshare-devel) for questions and discussion.

simplescope is fully functional for what it is.  The scope server controls access to the rest of the system, so a real scope server would have, at the very least, authentication.

`NEWSCOPE` is only for client-side Diamond applications like HyperFind, so you don't need it for DermShare.  You still need `CERTS` so diamondd knows which scope servers to trust.
