### ISSUE TITLE
What is the cookiecutter command for autosegment-cookie?

### ISSUE THREAD

**Issue by joegle** [cmusatyalab/dermshare#2]
What would be the cookiecutter command for autosegment-cookie if you have have 4 servers:
- scopeserver - 192.168.1.20
- dermclient - 192.168.1.30
- jsonblaster - 192.168.1.40
- diamond0 - 192.168.1.50 

On which host to run the cookiecutter command for autosegment-cookie?

And on which host do you place the autosegment-cookie in /etc/dermshare/ ?

Thanks

**Comment by bgilbert** [comment]
```
cookiecutter -b http://jsonblaster/ -s diamond0 -e 315360000 < /dev/null
```

You don't need any scope URLs, since the autosegment cookie is only used for evaluation.  It's easiest to run this on the scopeserver machine, since it already has the signing key.
