### ISSUE TITLE
OpenCV headers.

### ISSUE THREAD

**Issue by spressomonkey** [cmusatyalab/dermshare#4]
When trying to build dermshare, I had to change a few OpenCV include lines in autosegmenter/src/IPPInterface/IPPImage.h for everything to compile correctly. e.g. "cv.h" couldn't be found. Changing the import statements to <opencv/cv.h> fixed the problem. Submitting a pull request if upstream which upstream can use if they find it useful.

**Comment by bgilbert** [comment]
Thanks for the report and patch.
